#!/bin/sh

ssh ec2-user@ec2-18-222-231-126.us-east-2.compute.amazonaws.com <<EOF

    cd ~/bhook-mitao-be
    
    git pull origin main

    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash

    . ~/.nvm/nvm.sh
    
    nvm install v10.11.0
    
    npm install
    
    npm install -g nodemon pm2
    
    pm2 restart ecosystem.config.js
    
    exit

EOF